#==================== spring Setting =====================#
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



#==================== project Configuration =====================#
project:
  prefixPc:
file:
  server:
    http:
      prefix: http://127.0.0.1:16006/
    dir: F:/img
    image:
      dir: ${file.server.dir}/image
    testcase:
      dir: ${file.server.dir}/testcase
    type:
      image: jpg,png,bmp,gif,jpeg,psd,svg,JPG,PNG,BPM,GIF
      doc: doc,docx,xls,xlsx,txt,in,out






